### ISSUE TITLE
Activation Changes tab is sometimes not updated 

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-admin#34]
When I block or unblock an activation in Activation Changes tab, sometimes the most recent change is not visible. It seems to happen in approx. 20 % of cases.

<img width="1205" alt="screen shot 2018-04-04 at 15 19 49" src="https://user-images.githubusercontent.com/26658588/38310050-dfd09aea-381b-11e8-94f9-7f71217fce4b.png">

I suspect that the bug is caused by filter in which the "To" time filters out the most recent activation change.

**Comment by romanstrobl** [comment]
I found the root cause.

Change time in Java: 2018-04-04 22:22:45.545
Change time in database: 2018-04-04 22:22:46
Change time in filter: 2018/04/04 22:22:45

So, the database rounds the time to seconds (datetime doesn't support miliseconds), while filter applies "floor" on miliseconds.

At any case the previous fix of the bug should work fine.

**Comment by petrdvorak** [comment]
Wow, awesome - thank you for investigation. :)
